### ISSUE TITLE
重复解析

### ISSUE THREAD

**Issue by tomchan2015** [elltor/operate-log#1]
https://github.com/elltor/oplog/blob/bf75ad3ccd21b5dc76f69a19da138fbb5215a4dc/oplog-core/src/main/java/com/elltor/oplog/aspect/LogRecordAspect.java#L220
你好，想问一下这里为什么需要将 oldTemplate 重新解析一次？

**Comment by kymotz** [comment]
对于SpEL的解析，**自定义函数**可以选择在加 `@LogRecord` 注解方法**执行前执行或者之后执行**，因此第二次解析是对**后置自定义函数进行的解析**。

下面是日志工具自定义函数的接口：

```java
/**
 * 解析函数接口
 */

public interface IParseFunction {

    /**
     * 是否在aop织入方法执行前执行，织入前执行上下文中无法使用返回值和错误消息
     *
     * @return  boolean/false
     */
    default boolean executeBefore() {
        return false;
    }

    /**
     * 返回自定义SpEL的静态方法的方法对象
     *
     * @return
     */
    Method functionMethod();

}
```

假设我们实现一个通过订单 id 获取订单详细信息的自定义函数 orderDetail(id), 我们使用的模板是 `success = "订单号 :{#order.id}，订单详情： #orderDetail(#order.userid)"`

假设订单号为: 1000

则第一次解析后 success 的值为 ：`"订单号: 1000，订单详情： #orderDetail(#order.userid)"`

方法执行后第二次解析 success 的值为：`"订单号: 1000，订单详情： 用户：张XX，发往北京`
