### ISSUE TITLE
文中提到的多线程情况下如何保证栈的pop正常呢

### ISSUE THREAD

**Issue by Zorabi** [elltor/operate-log#2]

**Comment by kymotz** [comment]
我们知道 `ThreadLocal`（线程局部变量）是线程安全的，日志工具中存储方法上下文中的额外变量使用的是 `InheritableThreadLocal ` ，它与ThreadLocal有相同的线程安全性质且具有继承父线程数据的性质，这是为了增加日志注解（@LogRecord）的重入（e.g. 当一个方法中新启动一个线程并且内部方发使用了注解）。**回到你提问的问题，先看工具中是怎么使用： `InheritableThreadLocal<Stack<Map<String, Object>>>`，可以看到真实方法间共享的是一个Stack，Stack又是线程安全的，因此 ThreadLocal 和 Stack 共同确保多线程线程安全。**

**Comment by Zorabi** [comment]
> 
可能我描述的不清楚。我的问题是：

目前有 func1 func2 func3 三个方法，func1 中通过线程池执行 func2 func3。文中描述线程池情况下需要使用阿里 TTL，此处也同样使用。

那么在执行时，func1 很快执行完毕（并不关心 func2 func3的执行结果），func2、func3还在线程池中。假设，func2 比 func3的执行时间耗时更长，那么实际的执行时间是 func1 < func3 < func2

入栈顺序为  func1 func2 func3，在没有引入多线程执行时的出栈顺序为 func3 func2 func1。这个是没问题的。
在多线程时，出栈时由于func1 先于 func3 先于 func2 先执行完毕，出栈顺序则依次为 func1 func3 func2，那么 stack.pop 的值并不是串行时入栈的变量了

**Comment by kymotz** [comment]
了解你描述的问题了，经过思考和排查后😁，已经确定这是个 bug 🐛

问题根源在于：父子线程共享了 stack 对象，父线程退出后子线程未退出时，父线程操作 stack 影响子线程。

暂时的解决方案，经过测试后更新代码。

修改 LogRecordContext.java 初始化 `InheritableThreadLocal`,  重写创建 ThreadLocalMap 逻辑关键方法 `childValue`

```java
    // init, thread safe.
    static {
        LOCAL_VALUABLES = new InheritableThreadLocal<>() {
            @Override
            protected Stack<Map<String, Object>> initialValue() {
                return new Stack<>();
            }
            // 为子线程创建 ThreadLocalMap 时拷贝父线程的 stack
            @Override
            protected Stack<Map<String, Object>> childValue(Stack<Map<String, Object>> parentValue) {
                Stack<Map<String, Object>> copiedStack = new Stack<>();
                copiedStack.addAll(parentValue);
                return copiedStack;
            }
        };
    }
```

感谢提出这个问题😜，日后这个工具必将更加完善。

**Comment by Zorabi** [comment]
我还是存在疑虑，如果主线程未影响，而是两个子线程的退出顺序不一致的情况呢。

比如子任务 A 退出时本该弹出自己这一层的 stack，而此时因为某种原因，子任务 B 的 context 刚刚入栈，那在任务 B 实际使用context 的时候，就可能是用到任务 A 的这一层 stack了，自己的这一层会被任务 A pop 出去

**Comment by Zorabi** [comment]
我还是存在疑虑，如果主线程未影响，而是两个子线程的退出顺序不一致的情况呢。

比如子任务 A 退出时本该弹出自己这一层的 stack，而此时因为某种原因，子任务 B 的 context 刚刚入栈，那在任务 B 实际使用context 的时候，就可能是用到任务 A 的这一层 stack了，自己的这一层会被任务 A pop 出去

**Comment by kymotz** [comment]
子线程间不产出影响, 每个子线都会拷贝父线程的stack,  不是相同的栈, 因此不会影响对其他线程里的栈产生影响.  举个例子:

1. 父线程 a,  它的 ThreadLocal 值 stack = {map1, map2 } <-- 顶部
2. 父线程 a 创建两个子线程 b 和 c, 此时线程 b 和 c 拷贝线程 a 的ThreadLocal, stack_b = {map1, map2}  stack_c = {map1, map2}
3. 发生改变的情况 :
    1. 子线程间改变,  因为 stack_b 和 stack_c 并不共享,  所以不相互影响. 例如 stack_b 执行pop后, stack_b = {map1} stack_c = {map1, map2}
    2. 父线程改变, 同上.  stack_b 拷贝的 stack, 当 stack 改变不影响 stack_b 

----

工具中处理变量共享这样，变更时拷贝（Copy On Write）。

- 单线程时，嵌套使用，进入**内层**的方法时ThreadLocal中的stack入栈，新建 map 并拷贝栈顶 map 然后入栈，此时嵌套的**内层**方法 的Context Variables 共享**外层**的，对于 map 的操作（put、remove）不相互影响
- 多线程时，线程嵌套，子线程拷贝父线程的栈（准确应该父线程栈的栈顶元素）。子线程中也可能存在方法嵌套，同上。
